application: foodreview
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# Icon
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# Self-written css
- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

# Javascripts
- url: /scripts
  static_dir: scripts

# Twitter Bootstrap
- url: /bootstrap
  static_dir: bootstrap

- url: /
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest